name: Deploy Next.js with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 添加服务器到 known_hosts
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H 1.14.195.197 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 4. SSH 到服务器执行 Docker 部署
      - name: Deploy Docker container
        run: |
          ssh ubuntu@1.14.195.197 "
          mkdir -p ~/myproject &&
          cd ~/myproject || git clone git@github.com:Freelovelike/vercel-demo.git ~/myproject &&
          cd ~/myproject &&
          git pull &&
          docker build -t next-app . &&
          docker stop next-app || true &&
          docker rm next-app || true &&
          docker run -d --name next-app -p 3000:3000 next-app
          "
